# Autogenerated wrapper script for Doom_jll for armv7l-linux-musleabihf
export doom, doom1_wad

using SDL2_jll
using SDL2_mixer_jll
JLLWrappers.@generate_wrapper_header("Doom")
JLLWrappers.@declare_executable_product(doom)
JLLWrappers.@declare_file_product(doom1_wad)
function __init__()
    JLLWrappers.@generate_init_header(SDL2_jll, SDL2_mixer_jll)
    JLLWrappers.@init_executable_product(
        doom,
        "bin/doom",
    )

    JLLWrappers.@init_file_product(
        doom1_wad,
        "share/doom/doom1.wad",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
