# Autogenerated wrapper script for Doom_jll for x86_64-w64-mingw32
export doom

using SDL2_jll
using SDL2_mixer_jll
JLLWrappers.@generate_wrapper_header("Doom")
JLLWrappers.@declare_executable_product(doom)
function __init__()
    JLLWrappers.@generate_init_header(SDL2_jll, SDL2_mixer_jll)
    JLLWrappers.@init_executable_product(
        doom,
        "bin\\doom.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
